BEGIN TRANSACTION;

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100),
  email text UNIQUE NOT NULL,
  entries BIGINT DEFAULT 0,
  joined TIMESTAMP NOT NULL,
  pet VARCHAR(100) DEFAULT 'None',
  age SMALLINT DEFAULT 1 CHECK (age > 0)
);

COMMIT;